### ISSUE TITLE
Request Storm 

### ISSUE THREAD

**Issue by kenwdelong** [dahlb/hatch_rest_api#4]
I work at Hatch. We are being alerted by our production systems of some possible bugs in your project.  MQTT client connection attempts are being throttled by AWS:
![image](https://user-images.githubusercontent.com/6744405/160445170-ec8b307c-a290-4553-b8f0-d881825b8505.png)

AWS have strict limits on the number of connection attempts from a single client id:
![image](https://user-images.githubusercontent.com/6744405/160445292-104d90cf-9983-44c2-bb1d-6b6f6bf35790.png)
https://docs.aws.amazon.com/general/latest/gr/iot-core.html
![image](https://user-images.githubusercontent.com/6744405/160445382-093b7a66-11a5-4e2f-8383-3d56ebe9fd26.png)
https://docs.aws.amazon.com/iot/latest/developerguide/metrics_dimensions.html

From the Cloudwatch graph, it looks like connect requests are coming in at over 1/second, resulting in ClientIdThrottle events (resulting in my pager going off during the night :-)

I hope you can track down this bug and prevent the code from issuing so many client connection requests to MQTT.

**Comment by dahlb** [comment]
sorry this is happening, thanks for filing this bug report to let me know.  I'm still very new to iot and python, I'll start working on this today.

**Comment by kenwdelong** [comment]
Looking much better!  Thanks very much!

![image](https://user-images.githubusercontent.com/6744405/160474379-276575a8-4ee8-429a-abb0-309754355a61.png)
